Update cicd.yml

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -23,9 +23,10 @@ jobs:
           elif [[ "$file" == *.py ]]; then
             curl -v -n -X POST https://adb-2081951158852644.4.azuredatabricks.net/api/2.0/workspace/import \
               -H "Authorization: Bearer ${{ secrets.DATABRICKS_TOKEN }}" \
-              -F "path=/carbo-loading-UAT/$(basename "$file")" \
-              -F "format=SOURCE" \
-              -F "content=$(base64 "$file")" || echo "Failed to deploy $file"
+              -H "Content-Type: application/octet-stream" \
+              --data-binary "@$file" \
+              -d "path=/carbo-loading-UAT/$(basename "$file")" \
+              -d "format=SOURCE" || echo "Failed to deploy $file"
           else
             echo "Skipping $file - unsupported extension"
             continue
